#include "luafront.h"

#include <stdlib.h>
#include <string.h>

/* Generated by tools/embed-profile.py from profiles/lua55.syntax. */
static const char *const builtin_lua55_chunks[] = {
    "profile lua55;\n",
    "version \"5.5.0\";\n",
    "contextual \"global\";\n",
    "line_comment \"--\";\n",
    "lua_long_comment \"--\";\n",
    "\n",
    "rule chunk = block:body EOF => Chunk(body);\n",
    "rule repl_expr = exp:value EOF => Chunk(Block(Return(ExprList(value))));\n",
    "rule block = { stat:items } [ retstat:ret ] => Block(items, ret);\n",
    "\n",
    "rule stat = empty_stat | global_function_stat | global_decl | global_all | assign_stat | call_stat | label_stat | break_stat | goto_stat | do_stat | while_stat | repeat_stat | if_stat | numeric_for_stat | generic_for_stat | function_stat | local_function_stat | local_decl;\n",
    "rule empty_stat = \";\" => Empty();\n",
    "rule assign_stat = varlist:left \"=\" explist:right => Assign(left, right);\n",
    "rule call_stat = postfix:call => Pass(call);\n",
    "rule label_stat = \"::\" NAME:name \"::\" => Label(name);\n",
    "rule break_stat = \"break\" => Break();\n",
    "rule goto_stat = \"goto\" NAME:name => Goto(name);\n",
    "rule do_stat = \"do\" block:body \"end\" => Do(body);\n",
    "rule while_stat = \"while\" exp:cond \"do\" block:body \"end\" => While(cond, body);\n",
    "rule repeat_stat = \"repeat\" block:body \"until\" exp:cond => Repeat(body, cond);\n",
    "rule if_stat = \"if\" exp:cond \"then\" block:yes { elseif_part:elifs } [ else_part:no ] \"end\" => If(cond, yes, elifs, no);\n",
    "rule elseif_part = \"elseif\" exp:cond \"then\" block:body => ElseIf(cond, body);\n",
    "rule else_part = \"else\" block:body => Else(body);\n",
    "rule numeric_for_stat = \"for\" NAME:name \"=\" exp:first \",\" exp:last [ \",\" exp:step ] \"do\" block:body \"end\" => NumericFor(name, first, last, step, body);\n",
    "rule generic_for_stat = \"for\" namelist:names \"in\" explist:values \"do\" block:body \"end\" => GenericFor(names, values, body);\n",
    "rule function_stat = \"function\" funcname:name funcbody:body => FunctionDecl(name, body);\n",
    "rule local_function_stat = \"local\" \"function\" NAME:name funcbody:body => LocalFunction(name, body);\n",
    "rule global_function_stat = \"global\" \"function\" NAME:name funcbody:body => GlobalFunction(name, body);\n",
    "rule local_decl = \"local\" attnamelist:names [ \"=\" explist:values ] => Local(names, values);\n",
    "rule global_decl = \"global\" attnamelist:names [ \"=\" explist:values ] => Global(names, values);\n",
    "rule global_all = \"global\" [ attrib:attr ] \"*\" => GlobalAll(attr);\n",
    "\n",
    "rule retstat = \"return\" [ explist:values ] [ \";\" ] => Return(values);\n",
    "rule namelist = NAME:first { \",\" NAME:rest } => ParamList(first, rest);\n",
    "rule attnamelist = [ attrib:prefix ] attname:first { \",\" attname:rest } => DeclList(prefix, first, rest);\n",
    "rule attname = NAME:name [ attrib:attr ] => DeclName(name, attr);\n",
    "rule attrib = \"<\" NAME:name \">\" => Attr(name);\n",
    "rule varlist = postfix:first { \",\" postfix:rest } => VarList(first, rest);\n",
    "rule explist = exp:first { \",\" exp:rest } => ExprList(first, rest);\n",
    "\n",
    "rule exp = or_expr:value => Pass(value);\n",
    "rule or_expr = and_expr:first { or_tail:rest } => Fold(first, rest);\n",
    "rule or_tail = \"or\":op and_expr:value => Tail(op, value);\n",
    "rule and_expr = compare_expr:first { and_tail:rest } => Fold(first, rest);\n",
    "rule and_tail = \"and\":op compare_expr:value => Tail(op, value);\n",
    "rule compare_expr = bor_expr:first { compare_tail:rest } => Fold(first, rest);\n",
    "rule compare_tail = compop:op bor_expr:value => Tail(op, value);\n",
    "rule compop = \"<\" | \"<=\" | \">\" | \">=\" | \"==\" | \"~=\";\n",
    "rule bor_expr = bxor_expr:first { bor_tail:rest } => Fold(first, rest);\n",
    "rule bor_tail = \"|\":op bxor_expr:value => Tail(op, value);\n",
    "rule bxor_expr = band_expr:first { bxor_tail:rest } => Fold(first, rest);\n",
    "rule bxor_tail = \"~\":op band_expr:value => Tail(op, value);\n",
    "rule band_expr = shift_expr:first { band_tail:rest } => Fold(first, rest);\n",
    "rule band_tail = \"&\":op shift_expr:value => Tail(op, value);\n",
    "rule shift_expr = concat_expr:first { shift_tail:rest } => Fold(first, rest);\n",
    "rule shift_tail = shiftop:op concat_expr:value => Tail(op, value);\n",
    "rule shiftop = \"<<\" | \">>\";\n",
    "rule concat_expr = add_expr:left [ concat_tail:right ] => Right(left, right);\n",
    "rule concat_tail = \"..\":op concat_expr:value => Tail(op, value);\n",
    "rule add_expr = mul_expr:first { add_tail:rest } => Fold(first, rest);\n",
    "rule add_tail = addop:op mul_expr:value => Tail(op, value);\n",
    "rule addop = \"+\" | \"-\";\n",
    "rule mul_expr = unary_expr:first { mul_tail:rest } => Fold(first, rest);\n",
    "rule mul_tail = mulop:op unary_expr:value => Tail(op, value);\n",
    "rule mulop = \"*\" | \"/\" | \"//\" | \"%\";\n",
    "rule unary_expr = unary_pref | pow_expr;\n",
    "rule unary_pref = unop:op unary_expr:value => Unary(op, value);\n",
    "rule unop = \"-\" | \"not\" | \"#\" | \"~\";\n",
    "rule pow_expr = simple_expr:left [ pow_tail:right ] => Right(left, right);\n",
    "rule pow_tail = \"^\":op unary_expr:value => Tail(op, value);\n",
    "\n",
    "rule simple_expr = nil_expr | false_expr | true_expr | number_expr | string_expr | vararg_expr | functiondef | tableconstructor | postfix;\n",
    "rule nil_expr = \"nil\" => Nil();\n",
    "rule false_expr = \"false\" => Bool(\"false\");\n",
    "rule true_expr = \"true\" => Bool(\"true\");\n",
    "rule number_expr = NUMBER:value => Pass(value);\n",
    "rule string_expr = STRING:value => Pass(value);\n",
    "rule vararg_expr = \"...\" => Vararg();\n",
    "\n",
    "rule postfix = primary:base { suffix:tail } => Postfix(base, tail);\n",
    "rule primary = name_primary | paren_primary;\n",
    "rule name_primary = NAME:name => Pass(name);\n",
    "rule paren_primary = \"(\" exp:value \")\" => Paren(value);\n",
    "rule suffix = index_suffix | field_suffix | method_suffix | call_suffix;\n",
    "rule index_suffix = \"[\" exp:key \"]\" => IndexSuffix(key);\n",
    "rule field_suffix = \".\" NAME:name => FieldSuffix(name);\n",
    "rule method_suffix = \":\" NAME:name args:args => MethodSuffix(name, args);\n",
    "rule call_suffix = args:args => CallSuffix(args);\n",
    "\n",
    "rule args = paren_args | table_args | string_args;\n",
    "rule paren_args = \"(\" [ explist:values ] \")\" => Pass(values);\n",
    "rule table_args = tableconstructor:value => Pass(value);\n",
    "rule string_args = STRING:value => Pass(value);\n",
    "\n",
    "rule functiondef = \"function\" funcbody:body => FunctionExpr(body);\n",
    "rule funcname = NAME:first { funcfield:rest } [ funcmethod:method ] => FuncName(first, rest, method);\n",
    "rule funcfield = \".\" NAME:name => FuncField(name);\n",
    "rule funcmethod = \":\" NAME:name => FuncMethod(name);\n",
    "rule funcbody = \"(\" [ parlist:params ] \")\" block:body \"end\" => FunctionBody(params, body);\n",
    "rule parlist = named_parlist | vararg_parlist;\n",
    "rule named_parlist = namelist:names [ \",\" varargparam:vararg ] => Params(names, vararg);\n",
    "rule vararg_parlist = varargparam:vararg => Params(vararg);\n",
    "rule varargparam = \"...\" [ NAME:name ] => Vararg(name);\n",
    "\n",
    "rule tableconstructor = \"{\" [ fieldlist:fields ] \"}\" => Table(fields);\n",
    "rule fieldlist = field:first { field_tail:rest } [ fieldsep ] => List(first, rest);\n",
    "rule field_tail = fieldsep field:value => Pass(value);\n",
    "rule field = keyed_field | named_field | value_field;\n",
    "rule keyed_field = \"[\" exp:key \"]\" \"=\" exp:value => KeyedField(key, value);\n",
    "rule named_field = NAME:name \"=\" exp:value => NamedField(name, value);\n",
    "rule value_field = exp:value => ValueField(value);\n",
    "rule fieldsep = \",\" | \";\";\n",
};

LF_Profile *lf_profile_builtin_lua55(LF_Error *err) {
    size_t total = 0;
    size_t n = sizeof(builtin_lua55_chunks) / sizeof(builtin_lua55_chunks[0]);
    for (size_t i = 0; i < n; i++) total += strlen(builtin_lua55_chunks[i]);
    char *source = (char *)malloc(total + 1);
    if (source == NULL) abort();
    size_t off = 0;
    for (size_t i = 0; i < n; i++) {
        size_t len = strlen(builtin_lua55_chunks[i]);
        memcpy(source + off, builtin_lua55_chunks[i], len);
        off += len;
    }
    source[off] = '\0';
    LF_Profile *profile = lf_profile_load_memory(
        "=(builtin lua55.syntax)", source, off, err);
    free(source);
    if (profile != NULL)
        lf_profile_set_native_diag(profile);  /* trusted builtin */
    return profile;
}
