#!/usr/bin/env python3
"""Generate src/builtin_profile.c from profiles/lua55.syntax."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "profiles" / "lua55.syntax"
OUT = ROOT / "src" / "builtin_profile.c"


def c_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=True)


def render() -> str:
    text = SRC.read_text(encoding="utf-8")
    chunks = text.splitlines(keepends=True)
    body = "\n".join(f"    {c_string(chunk)}," for chunk in chunks)
    return f'''#include "luafront.h"\n\n#include <stdlib.h>\n#include <string.h>\n\n/* Generated by tools/embed-profile.py from profiles/lua55.syntax. */\nstatic const char *const builtin_lua55_chunks[] = {{\n{body}\n}};\n\nLF_Profile *lf_profile_builtin_lua55(LF_Error *err) {{\n    size_t total = 0;\n    size_t n = sizeof(builtin_lua55_chunks) / sizeof(builtin_lua55_chunks[0]);\n    for (size_t i = 0; i < n; i++) total += strlen(builtin_lua55_chunks[i]);\n    char *source = (char *)malloc(total + 1);\n    if (source == NULL) abort();\n    size_t off = 0;\n    for (size_t i = 0; i < n; i++) {{\n        size_t len = strlen(builtin_lua55_chunks[i]);\n        memcpy(source + off, builtin_lua55_chunks[i], len);\n        off += len;\n    }}\n    source[off] = '\\0';\n    LF_Profile *profile = lf_profile_load_memory(\n        "=(builtin lua55.syntax)", source, off, err);\n    free(source);\n    return profile;\n}}\n'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    generated = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != generated:
            print("src/builtin_profile.c is stale; run make regen-profile")
            return 1
        return 0
    OUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
